apiVersion: apps/v1
kind: Deployment
metadata:
  name: heart-disease-predictor
  labels:
    app: heart-disease-predictor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heart-disease-predictor
  template:
    metadata:
      labels:
        app: heart-disease-predictor
    spec:
      containers:
      - name: heart-disease-predictor
        image: gcr.io/elaborate-chess-461609-j9/heart-disease-predictor:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: heart-disease-predictor-service
spec:
  selector:
    app: heart-disease-predictor
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: heart-disease-predictor-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: heart-disease-predictor
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
